"""scan findings and permissions

Revision ID: a358fe1991a6
Revises: 0001_initial_schema
Create Date: 2026-08-15 00:21:03.940574

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.auth.rbac_seed import scan_resource_grants


# revision identifiers, used by Alembic.
revision: str = '0002_scan_findings_and_permissions'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _seed_scan_permissions() -> None:
    """Incremental grants for the new "scan" resource (§9). 0001 already
    seeded every other resource; re-running baseline_grants() in full here
    would violate the (role, resource, action) unique constraint, so this
    inserts only the new scan_resource_grants() rows."""
    role_permissions = sa.table(
        "role_permissions",
        sa.column("id", sa.Uuid()),
        sa.column("role", sa.String()),
        sa.column("resource", sa.String()),
        sa.column("action", sa.String()),
        sa.column("allowed", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(timezone.utc)
    rows = [
        {
            "id": uuid.uuid4(),
            "role": role,
            "resource": resource,
            "action": action,
            "allowed": True,
            "created_at": now,
        }
        for role, resource, action in scan_resource_grants()
    ]
    op.bulk_insert(role_permissions, rows)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_runs',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_jobs',
    sa.Column('scan_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('scan_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_job_id', sa.Uuid(), nullable=False),
    sa.Column('check_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('owasp_2025_category', sa.String(length=100), nullable=False),
    sa.Column('cwe_id', sa.String(length=20), nullable=False),
    sa.Column('portswigger_reference_url', sa.String(length=500), nullable=True),
    sa.Column('cvss_vector', sa.String(length=100), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('affected_endpoints', sa.JSON(), nullable=False),
    sa.Column('plain_language_summary', sa.Text(), nullable=False),
    sa.Column('technical_description', sa.Text(), nullable=False),
    sa.Column('steps_to_reproduce', sa.JSON(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('confirmation_status', sa.String(length=20), nullable=False),
    sa.Column('retest_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('request_raw', sa.Text(), nullable=False),
    sa.Column('response_raw', sa.Text(), nullable=False),
    sa.Column('screenshot_refs', sa.JSON(), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    _seed_scan_permissions()


def downgrade() -> None:
    role_permissions = sa.table("role_permissions", sa.column("resource", sa.String()))
    op.execute(role_permissions.delete().where(role_permissions.c.resource == "scan"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('findings')
    op.drop_table('agent_jobs')
    op.drop_table('scan_runs')
    # ### end Alembic commands ###
