"""phase 2 credential login config, review candidates, llm cost

Revision ID: 0003_phase2_review_candidates
Revises: 0002_scan_findings_and_permissions
Create Date: 2026-08-15 00:53:14.209196

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.auth.rbac_seed import review_candidate_resource_grants


# revision identifiers, used by Alembic.
revision: str = '0003_phase2_review_candidates'
down_revision: Union[str, None] = '0002_scan_findings_and_permissions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _seed_review_candidate_permissions() -> None:
    """Incremental grants for the new "review_candidate" resource (§9),
    same reasoning as 0002's _seed_scan_permissions: 0001/0002 already
    seeded every other resource, so this inserts only the new rows."""
    role_permissions = sa.table(
        "role_permissions",
        sa.column("id", sa.Uuid()),
        sa.column("role", sa.String()),
        sa.column("resource", sa.String()),
        sa.column("action", sa.String()),
        sa.column("allowed", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(timezone.utc)
    rows = [
        {
            "id": uuid.uuid4(),
            "role": role,
            "resource": resource,
            "action": action,
            "allowed": True,
            "created_at": now,
        }
        for role, resource, action in review_candidate_resource_grants()
    ]
    op.bulk_insert(role_permissions, rows)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_candidates',
    sa.Column('scan_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_job_id', sa.Uuid(), nullable=False),
    sa.Column('check_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity_guess', sa.String(length=16), nullable=False),
    sa.Column('affected_endpoint', sa.Text(), nullable=False),
    sa.Column('request_raw', sa.Text(), nullable=False),
    sa.Column('response_raw', sa.Text(), nullable=False),
    sa.Column('llm_reasoning', sa.Text(), nullable=False),
    sa.Column('llm_confidence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('credential_sets', sa.Column('login_endpoint', sa.String(length=500), nullable=True))
    op.add_column('credential_sets', sa.Column('login_method', sa.String(length=10), nullable=True))
    op.add_column('credential_sets', sa.Column('login_body_template', sa.String(length=1000), nullable=True))
    op.add_column('credential_sets', sa.Column('login_content_type', sa.String(length=100), nullable=True))
    op.add_column('credential_sets', sa.Column('token_response_path', sa.String(length=200), nullable=True))
    op.add_column(
        'scan_runs',
        sa.Column('llm_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###

    _seed_review_candidate_permissions()


def downgrade() -> None:
    role_permissions = sa.table("role_permissions", sa.column("resource", sa.String()))
    op.execute(role_permissions.delete().where(role_permissions.c.resource == "review_candidate"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_runs', 'llm_cost_usd')
    op.drop_column('credential_sets', 'token_response_path')
    op.drop_column('credential_sets', 'login_content_type')
    op.drop_column('credential_sets', 'login_body_template')
    op.drop_column('credential_sets', 'login_method')
    op.drop_column('credential_sets', 'login_endpoint')
    op.drop_table('review_candidates')
    # ### end Alembic commands ###
