"""phase 3 business rules

Revision ID: 0004_phase3_business_rules
Revises: 0003_phase2_review_candidates
Create Date: 2026-08-15 01:44:08.059898

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.auth.rbac_seed import business_rule_resource_grants


# revision identifiers, used by Alembic.
revision: str = '0004_phase3_business_rules'
down_revision: Union[str, None] = '0003_phase2_review_candidates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _seed_business_rule_permissions() -> None:
    """Incremental grants for the new "business_rule" resource (§9), same
    reasoning as 0002/0003's incremental seeds: 0001-0003 already seeded
    every other resource, so this inserts only the new rows."""
    role_permissions = sa.table(
        "role_permissions",
        sa.column("id", sa.Uuid()),
        sa.column("role", sa.String()),
        sa.column("resource", sa.String()),
        sa.column("action", sa.String()),
        sa.column("allowed", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(timezone.utc)
    rows = [
        {
            "id": uuid.uuid4(),
            "role": role,
            "resource": resource,
            "action": action,
            "allowed": True,
            "created_at": now,
        }
        for role, resource, action in business_rule_resource_grants()
    ]
    op.bulk_insert(role_permissions, rows)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rules',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    _seed_business_rule_permissions()


def downgrade() -> None:
    role_permissions = sa.table("role_permissions", sa.column("resource", sa.String()))
    op.execute(role_permissions.delete().where(role_permissions.c.resource == "business_rule"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_rules')
    # ### end Alembic commands ###
