"""phase 4 login macros

Revision ID: 0005_phase4_login_macros
Revises: 0004_phase3_business_rules
Create Date: 2026-08-15 13:50:18.607110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_phase4_login_macros'
down_revision: Union[str, None] = '0004_phase3_business_rules'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_macros',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('credential_set_id', sa.Uuid(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_set_id'], ['credential_sets.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_macros')
    # ### end Alembic commands ###
