"""phase 5 executive summary

Revision ID: 0006_phase5_executive_summary
Revises: 0005_phase4_login_macros
Create Date: 2026-08-20 21:46:23.443040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_phase5_executive_summary'
down_revision: Union[str, None] = '0005_phase4_login_macros'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_runs', sa.Column('executive_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_runs', 'executive_summary')
    # ### end Alembic commands ###
