"""phase 6 ai provider configs and fingerprint

Revision ID: 0007_phase6_ai_provider_configs
Revises: 0006_phase5_executive_summary
Create Date: 2026-08-20 22:05:46.185168

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.auth.rbac_seed import ai_provider_config_resource_grants


# revision identifiers, used by Alembic.
revision: str = '0007_phase6_ai_provider_configs'
down_revision: Union[str, None] = '0006_phase5_executive_summary'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _seed_ai_provider_config_permissions() -> None:
    """Incremental grants for the new "ai_provider_config" resource (§9),
    same reasoning as 0002-0004's incremental seeds: 0001-0006 already
    seeded every other resource, so this inserts only the new rows."""
    role_permissions = sa.table(
        "role_permissions",
        sa.column("id", sa.Uuid()),
        sa.column("role", sa.String()),
        sa.column("resource", sa.String()),
        sa.column("action", sa.String()),
        sa.column("allowed", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(timezone.utc)
    rows = [
        {
            "id": uuid.uuid4(),
            "role": role,
            "resource": resource,
            "action": action,
            "allowed": True,
            "created_at": now,
        }
        for role, resource, action in ai_provider_config_resource_grants()
    ]
    op.bulk_insert(role_permissions, rows)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('encrypted_api_key', sa.LargeBinary(), nullable=False),
    sa.Column('masked_reference', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scan_runs', sa.Column('ai_provider_config_id', sa.Uuid(), nullable=True))
    op.add_column('scan_runs', sa.Column('tech_stack_fingerprint', sa.JSON(), nullable=True))
    with op.batch_alter_table('scan_runs') as batch_op:
        batch_op.create_foreign_key(
            'fk_scan_runs_ai_provider_config_id', 'ai_provider_configs', ['ai_provider_config_id'], ['id']
        )
    # ### end Alembic commands ###

    _seed_ai_provider_config_permissions()


def downgrade() -> None:
    role_permissions = sa.table("role_permissions", sa.column("resource", sa.String()))
    op.execute(role_permissions.delete().where(role_permissions.c.resource == "ai_provider_config"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_runs') as batch_op:
        batch_op.drop_constraint('fk_scan_runs_ai_provider_config_id', type_='foreignkey')
        batch_op.drop_column('tech_stack_fingerprint')
        batch_op.drop_column('ai_provider_config_id')
    op.drop_table('ai_provider_configs')
    # ### end Alembic commands ###
