"""phase 6b oidc sso

Revision ID: 0008_phase6b_oidc_sso
Revises: 0007_phase6_ai_provider_configs
Create Date: 2026-08-20 22:34:36.922366

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.auth.rbac_seed import oidc_provider_config_resource_grants


# revision identifiers, used by Alembic.
revision: str = '0008_phase6b_oidc_sso'
down_revision: Union[str, None] = '0007_phase6_ai_provider_configs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _seed_oidc_provider_config_permissions() -> None:
    """Incremental grants for the new "oidc_provider_config" resource
    (§9), same reasoning as 0002-0007's incremental seeds: earlier
    migrations already seeded every other resource, so this inserts only
    the new rows."""
    role_permissions = sa.table(
        "role_permissions",
        sa.column("id", sa.Uuid()),
        sa.column("role", sa.String()),
        sa.column("resource", sa.String()),
        sa.column("action", sa.String()),
        sa.column("allowed", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(timezone.utc)
    rows = [
        {
            "id": uuid.uuid4(),
            "role": role,
            "resource": resource,
            "action": action,
            "allowed": True,
            "created_at": now,
        }
        for role, resource, action in oidc_provider_config_resource_grants()
    ]
    op.bulk_insert(role_permissions, rows)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_provider_configs',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('encrypted_client_secret', sa.LargeBinary(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('default_role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('oidc_subject', sa.String(length=255), nullable=True))
        batch_op.alter_column('hashed_password', existing_type=sa.VARCHAR(length=255), nullable=True)
        batch_op.create_index(op.f('ix_users_oidc_subject'), ['oidc_subject'], unique=False)
    # ### end Alembic commands ###

    _seed_oidc_provider_config_permissions()


def downgrade() -> None:
    role_permissions = sa.table("role_permissions", sa.column("resource", sa.String()))
    op.execute(role_permissions.delete().where(role_permissions.c.resource == "oidc_provider_config"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_index(op.f('ix_users_oidc_subject'))
        batch_op.alter_column('hashed_password', existing_type=sa.VARCHAR(length=255), nullable=False)
        batch_op.drop_column('oidc_subject')
    op.drop_table('oidc_provider_configs')
    # ### end Alembic commands ###
